name: $(Date:yyyyMMdd)$(Rev:.r)($(Build.BuildId))

trigger:
- tSQLtFacadeBuild

pr: none
schedules:
  - cron: 0 12 24 3 *
    displayName: Scheduled once(ish)
    branches:
      include:
      - CITesting
    always: true
  - cron: 15 12 24 3 *
    displayName: Scheduled once(ish)
    branches:
      include:
      - CITesting
    always: true

pool:
  vmImage: 'windows-latest'

parameters:
- name: SQLCMDPath
  type: string
  default: 'C:\Program Files\Microsoft SQL Server\110\Tools\Binn'
- name: RequestingBuildId
  type: string
  default: 'NULL'
- name: VMMatrix
  type: object
  default: [{"name":"S3",'SQLVersionEdition':'2016'},{"name":"S4",'SQLVersionEdition':'2017'},{"name":"S5",'SQLVersionEdition':'2019'}]



variables:
  - name: NamePreFix
    value: 'tSQLtCI_DevTestLab_'
  - name: ArtifactBranchName
    value: tSQLt$(Build.SourceVersion)

stages:
- stage: antCallTesting
  jobs:
  - job:
    steps:
    - checkout: self
      clean: true
      lfs: false
      path: tSQLt

    - task: PowerShell@2
      name: Find_SQLCMD
      inputs:
        targetType: 'inline'
        script: |
          $x = get-ChildItem -path C:\program* -include sqlcmd.exe -recurse -ErrorAction Ignore
          $x|%{$_.FullName}