# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)($(Build.BuildId))(SQL ${{ parameters.SQLVersionEdition }})

trigger: none
pr: none
schedules:
  - cron: 0,15 12 * * mon,tue,wed,fri
    displayName: Scheduled once(ish)
    branches:
      include:
      - CITesting
    always: true

pool:
  vmImage: 'vs2017-win2016'

parameters:
- name: SQLVersionEdition
  type: string
  default: '2016'
- name: RequestingBuildId
  type: string
  default: 'NULL'

variables:
  NamePreFix: 'tSQLtCI_'


steps:

- task: CmdLine@2
  condition: false
  inputs:
    script: |
      echo end pipeline here      
      echx

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    KeyVaultName: 'tSQLtSigningKey'
    SecretsFilter: '*'


## step to decide if a new machine needs to be created

- task: PowerShell@2
  name: Generate_DevTest_Lab_Name
  inputs:
    targetType: 'inline'
    script: |
      $DevTestLabName = If ([string]::IsNullOrEmpty($env:DevTestLabNameOverride)) {("$(NamePreFix)" + (Get-Date).tostring(“yyyyMMdd”) + '_${{parameters.SQLVersionEdition}}_' + $(Build.BuildId))} else {($env:DevTestLabNameOverride)}
      $DevTestLabRGName = $DevTestLabName+'_RG'
      $DevTestLabVNetName = $DevTestLabName+'_VNet0001'
      $vmName = If ([string]::IsNullOrEmpty($env:vmNameOverride)) {('V$(Build.BuildId)-${{ parameters.SQLVersionEdition }}###############').substring(0,15).replace('#','')} else {($env:vmNameOverride)}
      Write-Host 'DevTestLabRGName: ' $DevTestLabRGName
      Write-Host "##vso[task.setvariable variable=DevTestLabRGName;]$DevTestLabRGName"
      Write-Host 'DevTestLabName: ' $DevTestLabName
      Write-Host "##vso[task.setvariable variable=DevTestLabName;]$DevTestLabName"
      Write-Host 'DevTestLabVNetName: ' $DevTestLabVNetName
      Write-Host "##vso[task.setvariable variable=DevTestLabVNetName;]$DevTestLabVNetName"
      Write-Host 'vmName: ' $vmName
      Write-Host "##vso[task.setvariable variable=vmName;]$vmName"

- task: AzurePowerShell@4
  name: Create_Resource_Group
  condition: and(succeeded(), eq(variables['CreateNewEnvironment'], '1'))
  inputs:
    azurePowerShellVersion: 'LatestVersion'
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    ScriptType: 'InlineScript'
    Inline: |
      Write-Host 'Creating Resource Group:' $(DevTestLabRGName)
      ##Set-PSDebug -Trace 1;
      New-AzResourceGroup -Name "$(DevTestLabRGName)" -Location "East US 2" -Tag @{Department="tSQLtCI"; Ephemeral="True"} -Force
      Set-PSDebug -Trace 0;
      Write-Host 'Done.'

##Need to make sure we're validating the right templates here (and remove unused ones from git repository)

- task: AzureResourceManagerTemplateDeployment@3
  name: Validate_VNet_ArmTemplate
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    subscriptionId: '58c04a99-5b92-410c-9e41-10262f68ca80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(DevTestLabRGName)'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CI/CreateVNetTemplate.json'
    deploymentMode: 'Validation'

- task: AzureResourceManagerTemplateDeployment@3
  name: Validate_DTL_ArmTemplate
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    subscriptionId: '58c04a99-5b92-410c-9e41-10262f68ca80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(DevTestLabRGName)'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CI/CreateDevTestLabTemplate.json'
    deploymentMode: 'Validation'

- task: AzureResourceManagerTemplateDeployment@3
  name: Validate_VM_ArmTemplate
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    subscriptionId: '58c04a99-5b92-410c-9e41-10262f68ca80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(DevTestLabRGName)'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CI/CreateVMTemplate.json'
    deploymentMode: 'Validation'

- task: AzureResourceManagerTemplateDeployment@3
  name: Validate_VMSchedule_ArmTemplate
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    subscriptionId: '58c04a99-5b92-410c-9e41-10262f68ca80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(DevTestLabRGName)'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CI/CreateVMScheduleTemplate.json'
    deploymentMode: 'Validation'

- task: AzureResourceManagerTemplateDeployment@3
  name: Validate_SQLVirtualMachine_ArmTemplate
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    subscriptionId: '58c04a99-5b92-410c-9e41-10262f68ca80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(DevTestLabRGName)'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CI/CreateSQLVirtualMachineTemplate.json'
    deploymentMode: 'Validation'

- task: AzurePowerShell@4
  name: Create_VNet
  condition: and(succeeded(), eq(variables['CreateNewEnvironment'], '1'))
  inputs:
    azurePowerShellVersion: 'LatestVersion'
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    ScriptType: 'InlineScript'
    Inline: |
      Set-Location $(Build.Repository.LocalPath)
      ##Set-PSDebug -Trace 1;
      $VNet = New-AzResourceGroupDeployment -ResourceGroupName "$(DevTestLabRGName)" -TemplateFile "CI/CreateVNetTemplate.json" -VNet_name "$(DevTestLabVNetName)" -SQL_Port "$(SQL_Port)"
      Set-PSDebug -Trace 0;
      $DevTestLabVNetSubnetName = $VNet.Outputs.subnetName.Value
      Write-Host 'DevTestLabVNetSubnetName: ' $DevTestLabVNetSubnetName
      Write-Host "##vso[task.setvariable variable=DevTestLabVNetSubnetName;]$DevTestLabVNetSubnetName"

- task: AzurePowerShell@4
  name: Create_DevTest_Lab_With_Other_Resources
  condition: and(succeeded(), eq(variables['CreateNewEnvironment'], '1'))
  env:
    LABVMSHUTDOWNNOTIFICATIONEMAIL: $(NotificationEmail)
    LABVMSHUTDOWNNOTIFICATIONURL: $(tSQLt-Slack-CI-Pipeline-WebHook)
  inputs:
    azurePowerShellVersion: 'LatestVersion'
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    ScriptType: 'InlineScript'
    Inline: |
      Set-Location $(Build.Repository.LocalPath)
      ##Set-PSDebug -Trace 1;
      New-AzResourceGroupDeployment -ResourceGroupName "$(DevTestLabRGName)" -TemplateFile "CI/CreateDevTestLabTemplate.json" -newLabName "$(DevTestLabName)" -VNetName "$(DevTestLabVNetName)" -SubNetName "$(DevTestLabVNetSubnetName)" -labVmShutDownNotificationEmail "$env:LABVMSHUTDOWNNOTIFICATIONEMAIL" -labVmShutDownNotificationURL "$env:LABVMSHUTDOWNNOTIFICATIONURL"
      Set-PSDebug -Trace 0;

- task: AzurePowerShell@4
  name: CreateVMAndMore
  env:
    USER_NAME: $(tSQLt-UserForCIEnvironment-UserName)
    PASSWORD: $(tSQLt-UserForCIEnvironment-Password)
    CONTACT_EMAIL: $(NotificationEmail)
  inputs:
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    ScriptType: 'FilePath'
    ScriptPath: 'CI/CreateVM.ps1'
    ScriptArguments: '-DTLRGName "$(DevTestLabRGName)" -DTLName "$(DevTestLabName)" -DTLVmName "$(vmName)" -DTLVNetName "$(DevTestLabVNetName)" -DTLVNetSubnetName "$(DevTestLabVNetSubnetName)" -SQLPort "$(SQL_Port)" -SQLVersionEdition "${{ parameters.SQLVersionEdition }}"' 
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@4
  name: UpdateAutoShutdown
  env:
    CONTACT_EMAIL: $(NotificationEmail)
    NOTIFICATION_URL: $(tSQLt-Slack-CI-Pipeline-WebHook)
  inputs:
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    azurePowerShellVersion: 'LatestVersion'
    ScriptType: 'InlineScript'
    Inline: |
      Set-Location $(Build.Repository.LocalPath)
      Write-Host 'Update VM AutoShutdown Schedule'
      $ShutDownTimeUTC = (Get-Date).toUniversalTime().AddHours(2).toString("HH:mm")
      ##Set-PSDebug -Trace 1;
      ##$VM = New-AzResourceGroupDeployment -ResourceGroupName "$(DevTestLabRGName)" -TemplateFile "CI/CreateDTLAutoShutdownTemplate.json" -labVmShutDownTime "$ShutDownTimeUTC" -DTLName "$(DevTestLabName)"  -labVmShutDownURL "$env:NOTIFICATION_URL"  -emailRecipient "$env:CONTACT_EMAIL"
      ##Set-AZDTLAutoShutdownPolicy -ResourceGroupName "$(DevTestLabRGName)" -LabName "$(DevTestLabName)" -Time ((Get-Date).toUniversalTime().AddMinutes(120)) -Enable
      Set-PSDebug -Trace 0;
      Write-Host 'Finished Updating VM AutoShutdown Schedule'
