# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)($(Build.BuildId))

trigger: none
pr: none
schedules:
  - cron: 0 12 24 3 *
    displayName: Scheduled once(ish)
    branches:
      include:
      - CITesting
    always: true
  - cron: 15 12 24 3 *
    displayName: Scheduled once(ish)
    branches:
      include:
      - CITesting
    always: true

pool:
  vmImage: 'vs2017-win2016'


parameters:
- name: SQLCMDPath
  type: string
  default: 'C:\Program Files\Microsoft SQL Server\110\Tools\Binn'
- name: RequestingBuildId
  type: string
  default: 'NULL'


variables:
  NamePreFix: 'tSQLtCI_DevTestLab_'

jobs:
- job: joba
  steps:

  - task: CmdLine@2
    name: AgentInfo
    inputs:
      script: |
        @ECHO ON
        systeminfo
        "${{ parameters.SQLCMDPath }}\SQLCMD" -?
        SET

  - task: PowerShell@2
    name: setVar
    inputs:
      targetType: 'inline'
      script: |
        $myvar = "foundyou"
        Write-Host "##vso[task.setvariable variable=myvar;isOutput=true]$myvar"


- job: jobb
  dependsOn: joba
  variables: 
    myvar: $[ dependencies.joba.outputs['setVar.myvar'] ]
  steps:

  - task: CmdLine@2
    name: AgentInfo
    inputs:
      script: |
        @ECHO ON
        systeminfo
        "${{ parameters.SQLCMDPath }}\SQLCMD" -?
        SET

  - task: PowerShell@2
    name: setVar
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "${{ variables['myvar'] }}"
        Write-Host $env:myvar






