# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)($(Build.BuildId))

trigger: none
pr: none
schedules:
  - cron: 0 12 24 3 *
    displayName: Scheduled once(ish)
    branches:
      include:
      - CITesting
    always: true
  - cron: 15 12 24 3 *
    displayName: Scheduled once(ish)
    branches:
      include:
      - CITesting
    always: true

pool:
  vmImage: 'vs2017-win2016'


parameters:
- name: SQLCMDPath
  type: string
  default: 'C:\Program Files\Microsoft SQL Server\110\Tools\Binn'
- name: RequestingBuildId
  type: string
  default: 'NULL'


variables:
  NamePreFix: 'tSQLtCI_DevTestLab_'

resources:
  repositories:
  - repository: tmp6
    type: github
    name: tSQLt/tmp6
    endpoint: GitHub-tSQLt-Robot

jobs:
- job: joba
  
  steps:

  - checkout: self
    clean: true
    fetchDepth: 1
    lfs: false
    path: tSQLt

  - checkout: tmp6
    clean: true
    fetchDepth: 1
    lfs: false
    path: tmp6
    persistCredentials: true

  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
      KeyVaultName: 'tSQLtSigningKey'
      SecretsFilter: '*'

  - task: CmdLine@2
    name: AgentInfo
    inputs:
      script: |
        @ECHO ON
        systeminfo
        "${{ parameters.SQLCMDPath }}\SQLCMD" -?
        SET
        ECHO $(Pipeline.Workspace)
        ECHO $(Agent.BuildDirectory)
        dir $(Pipeline.Workspace) /s

  - task: CmdLine@2
    name: GetCommitId
    inputs:
      script: |
        @ECHO ON
        ECHO %BUILD_SOURCEVERSION% >CommitId.txt


  - task: CmdLine@2
    name: StoreInArtifactRepo
    env:
      GITHUB_USERNAME: $(GitHubUserName)
      GITHUB_EMAIL: $(GitHubEmail)
    inputs:
      script: |
        @ECHO ON
        @ECHO -------------------------------
        @ECHO -------------------------------
        SET /p BuildSourceVersion=<CommitId.txt
        @ECHO -------------------------------
        @ECHO -------------------------------
        cd $(Pipeline.Workspace)\tmp6
        @ECHO %CD%
        @ECHO -------------------------------
        @ECHO -------------------------------
        git config --global user.email "%GITHUB_EMAIL%"
        git config --global user.name "%GITHUB_USERNAME%"
        @ECHO -------------------------------
        @ECHO -------------------------------
        git show
        @ECHO -------------------------------
        @ECHO -------------------------------
        git log
        @ECHO -------------------------------
        @ECHO -------------------------------
        git status
        @ECHO -------------------------------
        @ECHO -------------------------------
        git remote show origin
        @ECHO -------------------------------
        @ECHO -------------------------------
        git switch -c %BuildSourceVersion%
        @ECHO -------------------------------
        @ECHO -------------------------------
        git show >git_show.txt
        @ECHO -------------------------------
        @ECHO -------------------------------
        git add git_show.txt
        @ECHO -------------------------------
        git commit -m %BuildSourceVersion%
        @ECHO -------------------------------
        git push origin %BuildSourceVersion%
        @ECHO -------------------------------
        @ECHO -------------------------------
        git log
        @ECHO -------------------------------
        @ECHO -------------------------------
        git status
        @ECHO -------------------------------
        @ECHO -------------------------------
    