# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)($(Build.BuildId))

trigger: none
pr: none
schedules:
  - cron: 0 12 24 3 *
    displayName: Scheduled once(ish)
    branches:
      include:
      - CITesting
    always: true
  - cron: 15 12 24 3 *
    displayName: Scheduled once(ish)
    branches:
      include:
      - CITesting
    always: true

pool:
  vmImage: 'vs2017-win2016'


parameters:
- name: SQLCMDPath
  type: string
  default: 'C:\Program Files\Microsoft SQL Server\110\Tools\Binn'
- name: RequestingBuildId
  type: string
  default: 'NULL'


variables:
  NamePreFix: 'tSQLtCI_DevTestLab_'

resources:
  repositories:
  - repository: tSQLtArtifacts
    type: github
    name: Contoso/CommonTools
    endpoint: MyContosoServiceConnection

jobs:
- job: joba
  
  steps:

  - checkout: self
    clean: true
    fetchDepth: 1
    lfs: false

  - checkout: none

  - task: CmdLine@2
    name: AgentInfo
    inputs:
      script: |
        @ECHO ON
        systeminfo
        "${{ parameters.SQLCMDPath }}\SQLCMD" -?
        SET
        ECHO $(Pipeline.Workspace)
        ECHO $(Agent.BuildDirectory)
        dir -S $(Pipeline.Workspace)

