name: $(Date:yyyyMMdd)$(Rev:.r)($(Build.BuildId))

trigger: none
pr: none

pool:
  vmImage: 'vs2017-win2016'


variables:
  NamePreFix: 'tSQLtCI_Validate_'


steps:

- task: AzurePowerShell@4
  name: Create_Resource_Group
  inputs:
    azurePowerShellVersion: 'LatestVersion'
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    ScriptType: 'InlineScript'
    Inline: |
      $DevTestLabRGName = "$(NamePreFix)" + (Get-Date).tostring(“yyyyMMdd”) + $(Build.BuildId)+'_RG'
      Write-Host 'Creating Resource Group:' $(DevTestLabRGName)

      New-AzResourceGroup -Name "$(DevTestLabRGName)" -Location "East US 2" -Tag @{Department="tSQLtCI"; Ephemeral="True"} -Force

      Write-Host 'DevTestLabRGName: ' $DevTestLabRGName
      Write-Host "##vso[task.setvariable variable=DevTestLabRGName;]$DevTestLabRGName"
      Write-Host 'Done.'

##Need to make sure we're validating the right templates here (and remove unused ones from git repository)

- task: AzureResourceManagerTemplateDeployment@3
  name: Validate_VNet_ArmTemplate
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    subscriptionId: '58c04a99-5b92-410c-9e41-10262f68ca80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(DevTestLabRGName)'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CI/CreateVNetTemplate.json'
    deploymentMode: 'Validation'

- task: AzureResourceManagerTemplateDeployment@3
  name: Validate_DTL_ArmTemplate
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    subscriptionId: '58c04a99-5b92-410c-9e41-10262f68ca80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(DevTestLabRGName)'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CI/CreateDevTestLabTemplate.json'
    deploymentMode: 'Validation'

- task: AzureResourceManagerTemplateDeployment@3
  name: Validate_VM_ArmTemplate
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    subscriptionId: '58c04a99-5b92-410c-9e41-10262f68ca80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(DevTestLabRGName)'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CI/CreateVMTemplate.json'
    deploymentMode: 'Validation'

- task: AzureResourceManagerTemplateDeployment@3
  name: Validate_SQLVirtualMachine_ArmTemplate
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    subscriptionId: '58c04a99-5b92-410c-9e41-10262f68ca80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(DevTestLabRGName)'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CI/CreateSQLVirtualMachineTemplate.json'
    deploymentMode: 'Validation'

- task: AzurePowerShell@4
    name: Remove_Resource_Group
    inputs:
      azurePowerShellVersion: 'LatestVersion'
      azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
      ScriptType: 'InlineScript'
      Inline: |
        Write-Host 'Removing Resource Group:' $(DevTestLabRGName)
  
        Remove-AzResourceGroup  -name "$(DevTestLabRGName)" -Force

        Write-Host 'Done.'
  