theme: jekyll-theme-dinky
title: tSQLt - Database Unit Testing for SQL Server
description: tSQLt is the open source framework for unit testing on SQL Server
            [User guide](https://docs.tsqlt.org/user-guide/)